ui: tape
capabilities:
  record-video: false
  record-screenshots: false
browsers:
  - name: android
    version: [4.4,5.0]
    platform: Linux
  - name: firefox
    version: [37,38]
    platform: Windows 2012 R2
  - name: chrome
    version: [42,43]
    platform: Windows 2012 R2
  - name: ie
    version: 9..11
    platform: Windows 2008
  - name: safari
    version: 7..latest
  - name: ipad
    version: [6.1,7.1,8.1..latest]
  - name: opera
    version: latest
    platform: Windows 2003
